In [43]:
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import Table,bindparam, and_, text
from sqlalchemy.ext.declarative import declarative_base

In [44]:
conn = sa.create_engine("mysql+pymysql://CMARCINIAK:ifpri360@localhost/comtrade?charset=utf8mb4")

In [45]:
#query = "SELECT classification,year,commodity_code,partner_iso,reporter_iso,value,quantity,netweight_kg,kg_conversion_factor,qty_unit,trade_flow FROM comtradehs2015 where trade_flow_code < 3 and commodity_code like '0%%';"

#data = pd.read_sql(query,conn)

In [46]:
def make_query(number):
    query = "SELECT classification,year,commodity_code,partner_iso,reporter_iso,value,quantity,netweight_kg,kg_conversion_factor,qty_unit,trade_flow FROM comtradehs2015 where trade_flow_code < 3 and commodity_code like '{0}%%';"
    return query.format(str(number))

chapters = [0,1,20,21,22,23,24,50,51]

queries = list(map(make_query,chapters))
data = pd.DataFrame()
for query in queries:
    table = pd.read_sql(query,conn)
    data = pd.concat([data,table])

In [47]:
data.commodity_code.map(type).unique()

array([<class 'str'>], dtype=object)

In [48]:
data.commodity_code.map(lambda x: x[0:4])

0        0101
1        0101
2        0101
3        0101
4        0101
5        0101
6        0101
7        0101
8        0101
9        0101
10       0101
11       0101
12       0101
13       0101
14       0101
15       0101
16       0101
17       0101
18       0101
19       0101
20       0101
21       0101
22       0101
23       0101
24       0101
25       0101
26       0101
27       0101
28       0101
29       0101
         ...
35324    5113
35325    5113
35326    5113
35327    5113
35328    5113
35329    5113
35330    5113
35331    5113
35332    5113
35333    5113
35334    5113
35335    5113
35336    5113
35337    5113
35338    5113
35339    5113
35340    5113
35341    5113
35342    5113
35343    5113
35344    5113
35345    5113
35346    5113
35347    5113
35348    5113
35349    5113
35350    5113
35351    5113
35352    5113
35353    5113
Name: commodity_code, dtype: object

In [49]:
#data['HS4'] = pd.Series(map( lambda x: x[0:4], data.commodity_code))
data['HS4'] = data.commodity_code.map(lambda x: x[0:4])

In [110]:
agg = data.groupby(["HS4","reporter_iso","partner_iso","trade_flow","year"],as_index=False).sum()

In [138]:
agg[agg.reporter_iso=="BEL"]

,HS4,reporter_iso,partner_iso,trade_flow,year,value,quantity,netweight_kg
112,0101,BEL,ARE,Export,2015,1075670.0,63.0,NaN
113,0101,BEL,ARE,Import,2015,118005.0,11.0,5353.0
114,0101,BEL,ARG,Export,2015,110582.0,11.0,NaN
115,0101,BEL,BGR,Import,2015,7405.0,13.0,336.0
116,0101,BEL,BHR,Export,2015,344866.0,20.0,NaN
117,0101,BEL,BOL,Export,2015,88399.0,4.0,NaN
118,0101,BEL,BRA,Export,2015,4001849.0,132.0,NaN
119,0101,BEL,BRA,Import,2015,14938.0,2.0,678.0
120,0101,BEL,CAN,Export,2015,3301500.0,91.0,NaN
121,0101,BEL,CAN,Import,2015,12458.0,1.0,565.0
122,0101,BEL,CHE,Export,2015,5282411.0,135.0,NaN
123,0101,BEL,CHE,Import,2015,707285.0,169.0,27384.0
124,0101,BEL,CHL,Export,2015,945515.0,36.0,NaN
125,0101,BEL,CHN,Export,2015,2004790.0,78.0,NaN
126,0101,BEL,COD,Export,2015,8540.0,1.0,NaN
127,0101,BEL,COL,Export,2015,975354.0,38.0,NaN
128,0101,BEL,CYP,Import,2015,416771.0,1.0,18906.0
129,0101,BEL,CZE,Export,2015,1453720.0,33.0,NaN
130,0101,BEL,DEU,Export,2015,3192850.0,136.0,NaN
131,0101,BEL,DEU,Import,2015,3430078.0,460.0,28105.0
132,0101,BEL,DNK,Export,2015,479800.0,15.0,NaN
133,0101,BEL,DNK,Import,2015,277161.0,385.0,12338.0
134,0101,BEL,ECU,Export,2015,308675.0,11.0,NaN
135,0101,BEL,EGY,Export,2015,1809902.0,97.0,NaN
136,0101,BEL,ESP,Export,2015,1652830.0,8.0,NaN
137,0101,BEL,ESP,Import,2015,345350.0,38.0,1942.0
138,0101,BEL,FIN,Export,2015,456242.0,10.0,NaN
139,0101,BEL,FRA,Export,2015,2031334.0,318.0,NaN
140,0101,BEL,FRA,Import,2015,3673740.0,430.0,105614.0
141,0101,BEL,GBR,Export,2015,1700606.0,29.0,NaN
...,...,...,...,...,...,...,...,...
775838,5112,BEL,SVK,Export,2015,56398.0,1080.0,1080.0
775839,5112,BEL,SVK,Import,2015,69.0,1.0,1.0
775840,5112,BEL,SVN,Export,2015,747.0,14.0,14.0
775841,5112,BEL,SWE,Export,2015,84250.0,2072.0,2072.0
775842,5112,BEL,SWE,Import,2015,3187.0,63.0,63.0
775843,5112,BEL,THA,Export,2015,12359.0,200.0,200.0
775844,5112,BEL,TUN,Export,2015,8487.0,127.0,127.0
775845,5112,BEL,TUR,Export,2015,140273.0,3013.0,3013.0
775846,5112,BEL,TUR,Import,2015,132266.0,2192.0,2192.0
775847,5112,BEL,UKR,Export,2015,549039.0,12919.0,12919.0
775848,5112,BEL,UKR,Import,2015,996.0,9.0,9.0
775849,5112,BEL,USA,Export,2015,4137337.0,87119.0,87119.0
775850,5112,BEL,USA,Import,2015,21094.0,399.0,399.0
775851,5112,BEL,VNM,Export,2015,63885.0,1377.0,1377.0
775852,5112,BEL,ZAF,Export,2015,26283.0,580.0,580.0
779216,5113,BEL,CHE,Import,2015,1018.0,79.0,79.0
779217,5113,BEL,CHN,Import,2015,2120.0,164.0,164.0
779218,5113,BEL,COD,Export,2015,124.0,8.0,8.0
779219,5113,BEL,DEU,Export,2015,98.0,6.0,6.0
779220,5113,BEL,DEU,Import,2015,4023.0,312.0,312.0
779221,5113,BEL,ESP,Export,2015,647.0,41.0,41.0
779222,5113,BEL,FRA,Export,2015,33280.0,2116.0,2116.0
779223,5113,BEL,FRA,Import,2015,1456.0,113.0,113.0
779224,5113,BEL,HKG,Export,2015,8333.0,530.0,530.0
779225,5113,BEL,IND,Import,2015,626.0,48.0,48.0
779226,5113,BEL,ITA,Import,2015,8176.0,633.0,633.0
779227,5113,BEL,NLD,Export,2015,34.0,2.0,2.0
779228,5113,BEL,NLD,Import,2015,3260.0,253.0,253.0
779229,5113,BEL,PRT,Export,2015,61.0,4.0,4.0
779230,5113,BEL,TUR,Import,2015,58.0,5.0,5.0

In [139]:
#output = agg[['value','quantity','netweight_kg']]

In [140]:
output.to_csv("output_2015a.csv")

PermissionError: [Errno 13] Permission denied: 'output_2015a.csv'

In [137]:
output[output.quantity.isnull()]

           value  quantity  netweight_kg
0        20463.0       NaN        2250.0
1        10066.0       NaN        1000.0
2         9010.0       NaN          68.0
90       45899.0       NaN         800.0
91       10033.0       NaN        1000.0
92       89874.0       NaN        4900.0
93       19107.0       NaN        5700.0
94       16132.0       NaN         500.0
95       11905.0       NaN        1000.0
96       17140.0       NaN         400.0
97      837809.0       NaN      541100.0
98        5322.0       NaN         300.0
99        7982.0       NaN         600.0
100      32089.0       NaN        1400.0
101      17783.0       NaN        1300.0
102       5537.0       NaN         500.0
149       6466.0       NaN           NaN
171       6211.0       NaN           NaN
188       5943.0       NaN        8300.0
189        456.0       NaN       20000.0
190        707.0       NaN        1300.0
232      25105.0       NaN         651.0
233       9719.0       NaN        5490.0
234       1632.0       NaN        1270.0
235         65.0       NaN          10.0
246       1500.0       NaN           1.0
247      72864.0       NaN       20605.0
277      24000.0       NaN        2314.0
278     127000.0       NaN        8861.0
284        479.0       NaN         600.0
...          ...       ...           ...
754636    1067.0       NaN           NaN
754638     119.0       NaN           NaN
754639   14703.0       NaN           NaN
761169     624.0       NaN           NaN
761170     255.0       NaN           NaN
761191  209146.0       NaN           NaN
761758    1221.0       NaN           NaN
762091    3426.0       NaN           NaN
762161     155.0       NaN           NaN
762565      62.0       NaN           NaN
762861      22.0       NaN           NaN
762876      91.0       NaN           NaN
762910     237.0       NaN           NaN
763765     949.0       NaN           NaN
763766    1541.0       NaN           NaN
764699    1000.0       NaN           NaN
765290      10.0       NaN           NaN
765364     119.0       NaN           NaN
770452   74746.0       NaN           NaN
771003    3000.0       NaN           NaN
771655     102.0       NaN           NaN
772119      10.0       NaN           NaN
772198     205.0       NaN           NaN
772200    2051.0       NaN           NaN
772300      44.0       NaN           NaN
772388     119.0       NaN           NaN
772391    2728.0       NaN           NaN
772394     523.0       NaN           NaN
776673   61956.0       NaN           NaN
777364   32900.0       NaN           NaN

[6360 rows x 3 columns]

In [146]:
a = pd.read_csv("output_2013b.csv",dtype={'HS4':str})
b = pd.read_csv("output_2014b.csv",dtype={'HS4':str})
c = pd.read_csv("output_2015b.csv",dtype={'HS4':str})

In [147]:
out = pd.concat([a,b,c])
# = out['']

In [148]:
out['VALUE (1000USD)'] = out.value/1000
out['REPORTER [ISO 3 LETTER]'] = out['reporter_iso']
out['PARTNER [ISO 3 LETTER]'] = out['partner_iso']
out['HS4 [4 digit]'] = out['HS4']
out['YEAR'] = out['year']
out['VOLUME (M Tons)'] = out['netweight_kg']/1000
out['FLOWS (X or M)'] = out.trade_flow.map({"Export":"X","Import":"M"})
outfile = out[['REPORTER [ISO 3 LETTER]','PARTNER [ISO 3 LETTER]','HS4 [4 digit]','FLOWS (X or M)','YEAR','VALUE (1000USD)','VOLUME (M Tons)'] ]

In [150]:
outfile.columns

Index(['REPORTER [ISO 3 LETTER]', 'PARTNER [ISO 3 LETTER]', 'HS4 [4 digit]',
       'FLOWS (X or M)', 'YEAR', 'VALUE (1000USD)', 'VOLUME (M Tons)'],
      dtype='object')

In [151]:
outfile.to_csv("template_COMTRADE.csv")

In [116]:
len(outfile)

2372646

In [127]:
product_codes = outfile[outfile['VOLUME (M Tons)'].isnull()].groupby(["YEAR"])["HS4 [4 digit]"].value_counts()

In [131]:
product_codes[2015]

HS4 [4 digit]
0106    309
0101    299
0301    271
0604    252
2106    225
1209    204
0511    132
1515     99
0603     72
0602     69
1206     52
0105     47
0504     43
1301     37
1504     36
1212     35
1208     31
1207     30
5007     27
1401     23
5112     23
0508     22
1510     22
2201     21
1001     19
1008     19
2403     19
0510     18
2003     17
0410     16
       ...
1806      4
5102      4
0102      3
0206      3
0305      3
0402      3
0703      3
1108      3
1513      3
2102      3
2306      3
5105      3
5109      3
0210      2
0302      2
0304      2
0809      2
1522      2
2009      2
5104      2
0208      1
0408      1
0714      1
1003      1
1103      1
1104      1
1205      1
1702      1
2008      1
2204      1
Name: HS4 [4 digit], dtype: int64

In [132]:
outfile[outfile['VOLUME (M Tons)'].isnull()].groupby(["HS4 [4 digit]"])["REPORTER [ISO 3 LETTER]"].value_counts()

HS4 [4 digit]  REPORTER [ISO 3 LETTER]
0101           USA                        241
               BEL                        164
               ZAF                         98
               CAN                         85
               THA                         70
               CHL                         37
               SGP                         31
               JPN                         25
               IND                         24
               BRN                         23
               MEX                         22
               MYS                         21
               PAK                         16
               HKG                         15
               LKA                          9
               MUS                          8
               NGA                          7
               VNM                          6
               EGY                          5
               ISR                          5
               MNG                          4
               NPL                          4
               BMU                          3
               BWA                          3
               DOM                          3
               PSE                          3
               KEN                          1
               MLT                          1
               PLW                          1
               ROU                          1
                                         ...
5108           TON                          1
               VNM                          1
5109           EGY                          1
               ISR                          1
               PSE                          1
5110           SWE                          6
               AUT                          5
               DOM                          5
               THA                          2
               ZAF                          2
               HKG                          1
               ISR                          1
               MLT                          1
5111           SGP                          8
5112           SGP                         21
               IND                          3
               DOM                          1
               MEX                          1
               VNM                          1
5113           CHN                         35
               BEL                         16
               IND                         12
               SGP                          7
               VNM                          5
               ISR                          2
               MEX                          2
               MNG                          2
               SWE                          2
               WSM                          2
               NGA                          1
Name: REPORTER [ISO 3 LETTER], dtype: int64

In [153]:
outfile[outfile["VOLUME (M Tons)"]==0]

,REPORTER [ISO 3 LETTER],PARTNER [ISO 3 LETTER],HS4 [4 digit],FLOWS (X or M),YEAR,VALUE (1000USD),VOLUME (M Tons)
185,BEL,ARE,0101,X,2013,407.566,0.0
187,BEL,ARG,0101,X,2013,82.055,0.0
188,BEL,AUT,0101,X,2013,37.585,0.0
189,BEL,BHR,0101,X,2013,20.713,0.0
190,BEL,BOL,0101,X,2013,6.420,0.0
191,BEL,BRA,0101,X,2013,9196.386,0.0
192,BEL,BWA,0101,X,2013,172.872,0.0
193,BEL,CAN,0101,X,2013,2469.010,0.0
195,BEL,CHE,0101,X,2013,9651.890,0.0
197,BEL,CHL,0101,X,2013,498.003,0.0
198,BEL,CHN,0101,X,2013,223.061,0.0
199,BEL,COD,0101,X,2013,22.704,0.0
200,BEL,COL,0101,X,2013,1738.560,0.0
202,BEL,DEU,0101,X,2013,3158.830,0.0
204,BEL,DNK,0101,X,2013,639.990,0.0
206,BEL,DZA,0101,X,2013,11.127,0.0
207,BEL,ECU,0101,X,2013,512.593,0.0
208,BEL,EGY,0101,X,2013,1386.680,0.0
212,BEL,FRA,0101,X,2013,10543.790,0.0
214,BEL,GBR,0101,X,2013,3552.310,0.0
216,BEL,GRC,0101,X,2013,976.676,0.0
217,BEL,IRL,0101,X,2013,2556.290,0.0
220,BEL,ISR,0101,X,2013,349.662,0.0
222,BEL,ITA,0101,X,2013,308.710,0.0
224,BEL,JPN,0101,X,2013,10185.400,0.0
225,BEL,KOR,0101,X,2013,445.193,0.0
226,BEL,KWT,0101,X,2013,22.704,0.0
227,BEL,LBY,0101,X,2013,2024.220,0.0
228,BEL,LUX,0101,X,2013,92.148,0.0
230,BEL,MAR,0101,X,2013,198.631,0.0
...,...,...,...,...,...,...,...
775125,SGP,CHN,5111,M,2015,412.969,0.0
775126,SGP,GBR,5111,M,2015,139.525,0.0
775127,SGP,IDN,5111,X,2015,140.967,0.0
775128,SGP,IND,5111,M,2015,51.870,0.0
775129,SGP,ITA,5111,M,2015,206.345,0.0
775130,SGP,MYS,5111,X,2015,67.897,0.0
775131,SGP,USA,5111,M,2015,19.605,0.0
776673,DOM,ESP,5112,M,2015,61.956,0.0
777364,IND,THA,5112,M,2015,32.900,0.0
778690,SGP,ARE,5112,X,2015,156.041,0.0
778691,SGP,CHE,5112,M,2015,197.157,0.0
778692,SGP,CHN,5112,X,2015,35.581,0.0
778693,SGP,CHN,5112,M,2015,1427.375,0.0
778694,SGP,DEU,5112,M,2015,674.631,0.0
778695,SGP,ECU,5112,X,2015,35.786,0.0
778696,SGP,GBR,5112,X,2015,81.528,0.0
778697,SGP,GBR,5112,M,2015,663.807,0.0
778698,SGP,HKG,5112,X,2015,208.439,0.0
778699,SGP,IDN,5112,X,2015,298.942,0.0
778700,SGP,IND,5112,X,2015,1051.290,0.0
778701,SGP,IND,5112,M,2015,138.931,0.0
778702,SGP,IRL,5112,M,2015,139.025,0.0
778703,SGP,ITA,5112,M,2015,2608.076,0.0
778704,SGP,KHM,5112,X,2015,53.953,0.0
778705,SGP,MMR,5112,X,2015,41.904,0.0
778706,SGP,MYS,5112,X,2015,405.706,0.0
778707,SGP,THA,5112,X,2015,385.776,0.0
778708,SGP,THA,5112,M,2015,69.113,0.0
778709,SGP,USA,5112,M,2015,93.536,0.0
778710,SGP,VNM,5112,X,2015,277.025,0.0

In [152]:
outfile[outfile["VOLUME (M Tons)"].isnull()].head()

Empty DataFrame
Columns: [REPORTER [ISO 3 LETTER], PARTNER [ISO 3 LETTER], HS4 [4 digit], FLOWS (X or M), YEAR, VALUE (1000USD), VOLUME (M Tons)]
Index: []

In [98]:
counts = outfile.groupby(["REPORTER [ISO 3 LETTER]","PARTNER [ISO 3 LETTER]","HS4 [4 digit]","FLOWS (X or M)","YEAR"]).count()

In [105]:
len(counts)
#len(counts[counts["VALUE (1000USD)"]==1])

2372646

In [106]:
gbr = a[a.reporter_iso=='BEL']
gbr[gbr.partner_iso=="ARG"]

,HS4,reporter_iso,partner_iso,year,value,VOLUME (M Tons),FLOWS (X or M)
725,0101,BEL,ARG,2013,121324,0.300,X
726,0101,BEL,ARG,2013,11069830,1876.001,M
11025,0102,BEL,ARG,2013,45143,5.713,X
11026,0102,BEL,ARG,2013,141782,260.490,M
25060,0104,BEL,ARG,2013,78151,0.865,X
31228,0105,BEL,ARG,2013,26119500,48282.300,M
40917,0106,BEL,ARG,2013,281180,62.486,X
40918,0106,BEL,ARG,2013,2018382,3132.987,M
57087,0201,BEL,ARG,2013,1525680,656.182,X
57088,0201,BEL,ARG,2013,11004029,1126.308,M
68317,0202,BEL,ARG,2013,111820,92.078,X
68318,0202,BEL,ARG,2013,898390,1112.538,M
80305,0203,BEL,ARG,2013,48429,21.390,X
80306,0203,BEL,ARG,2013,10275207,2502.792,M
91837,0204,BEL,ARG,2013,278961,39.723,M
103660,0205,BEL,ARG,2013,21071780,4253.070,M
106703,0206,BEL,ARG,2013,14985,13.234,M
118583,0207,BEL,ARG,2013,367522,152.485,X
118584,0207,BEL,ARG,2013,110601,48.324,M
134087,0208,BEL,ARG,2013,167766,18.279,M
141997,0209,BEL,ARG,2013,2789,0.400,X
147956,0210,BEL,ARG,2013,5515,1.760,X
147957,0210,BEL,ARG,2013,1936,0.236,M
158281,0301,BEL,ARG,2013,6801200,3878.400,M
168421,0302,BEL,ARG,2013,2871,1.621,X
168422,0302,BEL,ARG,2013,5725092,3599.021,M
182213,0303,BEL,ARG,2013,82120,7.235,X
182214,0303,BEL,ARG,2013,2348401,740.478,M
197683,0304,BEL,ARG,2013,32743,4.686,X
197684,0304,BEL,ARG,2013,1407877,257.940,M
...,...,...,...,...,...,...,...
286962,0408,BEL,ARG,2013,701623,115.000,M
291182,0409,BEL,ARG,2013,1310720,438.025,M
300391,0504,BEL,ARG,2013,1544100,334.200,M
309638,0507,BEL,ARG,2013,5490,0.270,M
316300,0511,BEL,ARG,2013,91119,91.209,X
325294,0602,BEL,ARG,2013,1553,0.567,X
325295,0602,BEL,ARG,2013,4090760,3071.860,M
333599,0603,BEL,ARG,2013,22,0.011,X
347318,0701,BEL,ARG,2013,1175,0.427,X
357483,0703,BEL,ARG,2013,87068,15.432,X
371340,0705,BEL,ARG,2013,399336,149.789,M
377296,0706,BEL,ARG,2013,220638,26.366,X
381979,0707,BEL,ARG,2013,19942,3.360,X
391783,0709,BEL,ARG,2013,2386284,400.408,X
391784,0709,BEL,ARG,2013,24696,25.406,M
402708,0710,BEL,ARG,2013,224559,144.278,X
428127,0713,BEL,ARG,2013,1970316,1846.593,M
444508,0801,BEL,ARG,2013,33118,2.177,X
453057,0802,BEL,ARG,2013,61322,8.294,X
469750,0804,BEL,ARG,2013,25451,3.370,M
477708,0805,BEL,ARG,2013,5877478,4860.114,M
482631,0806,BEL,ARG,2013,69857,28.152,M
490551,0808,BEL,ARG,2013,748999,450.155,M
494665,0809,BEL,ARG,2013,87759,10.560,M
498084,0810,BEL,ARG,2013,2489144,228.771,M
503544,0811,BEL,ARG,2013,1400710,482.173,M
509605,0813,BEL,ARG,2013,118893,126.000,M
525329,0902,BEL,ARG,2013,841864,371.960,M
533825,0904,BEL,ARG,2013,1158,0.078,X
553431,0910,BEL,ARG,2013,1096,0.120,X

In [107]:
outfile[outfile["REPORTER [ISO 3 LETTER]"]=="BEL"]

,REPORTER [ISO 3 LETTER],PARTNER [ISO 3 LETTER],HS4 [4 digit],FLOWS (X or M),YEAR,VALUE (1000USD),VOLUME (M Tons)
185,BEL,ARE,0101,X,2013,407.566,NaN
186,BEL,ARE,0101,M,2013,7.303,0.406
187,BEL,ARG,0101,X,2013,82.055,NaN
188,BEL,AUT,0101,X,2013,37.585,NaN
189,BEL,BHR,0101,X,2013,20.713,NaN
190,BEL,BOL,0101,X,2013,6.420,NaN
191,BEL,BRA,0101,X,2013,9196.386,NaN
192,BEL,BWA,0101,X,2013,172.872,NaN
193,BEL,CAN,0101,X,2013,2469.010,NaN
194,BEL,CAN,0101,M,2013,13.279,0.739
195,BEL,CHE,0101,X,2013,9651.890,NaN
196,BEL,CHE,0101,M,2013,619.848,10.588
197,BEL,CHL,0101,X,2013,498.003,NaN
198,BEL,CHN,0101,X,2013,223.061,NaN
199,BEL,COD,0101,X,2013,22.704,NaN
200,BEL,COL,0101,X,2013,1738.560,NaN
201,BEL,CZE,0101,M,2013,40.533,2.254
202,BEL,DEU,0101,X,2013,3158.830,NaN
203,BEL,DEU,0101,M,2013,6989.043,130.203
204,BEL,DNK,0101,X,2013,639.990,NaN
205,BEL,DNK,0101,M,2013,968.064,42.017
206,BEL,DZA,0101,X,2013,11.127,NaN
207,BEL,ECU,0101,X,2013,512.593,NaN
208,BEL,EGY,0101,X,2013,1386.680,NaN
209,BEL,ESP,0101,X,2013,818.767,0.114
210,BEL,ESP,0101,M,2013,550.689,20.053
211,BEL,FIN,0101,M,2013,28.083,1.562
212,BEL,FRA,0101,X,2013,10543.790,NaN
213,BEL,FRA,0101,M,2013,7136.350,229.790
214,BEL,GBR,0101,X,2013,3552.310,NaN
...,...,...,...,...,...,...,...
775838,BEL,SVK,5112,X,2015,56.398,1.080
775839,BEL,SVK,5112,M,2015,0.069,0.001
775840,BEL,SVN,5112,X,2015,0.747,0.014
775841,BEL,SWE,5112,X,2015,84.250,2.072
775842,BEL,SWE,5112,M,2015,3.187,0.063
775843,BEL,THA,5112,X,2015,12.359,0.200
775844,BEL,TUN,5112,X,2015,8.487,0.127
775845,BEL,TUR,5112,X,2015,140.273,3.013
775846,BEL,TUR,5112,M,2015,132.266,2.192
775847,BEL,UKR,5112,X,2015,549.039,12.919
775848,BEL,UKR,5112,M,2015,0.996,0.009
775849,BEL,USA,5112,X,2015,4137.337,87.119
775850,BEL,USA,5112,M,2015,21.094,0.399
775851,BEL,VNM,5112,X,2015,63.885,1.377
775852,BEL,ZAF,5112,X,2015,26.283,0.580
779216,BEL,CHE,5113,M,2015,1.018,0.079
779217,BEL,CHN,5113,M,2015,2.120,0.164
779218,BEL,COD,5113,X,2015,0.124,0.008
779219,BEL,DEU,5113,X,2015,0.098,0.006
779220,BEL,DEU,5113,M,2015,4.023,0.312
779221,BEL,ESP,5113,X,2015,0.647,0.041
779222,BEL,FRA,5113,X,2015,33.280,2.116
779223,BEL,FRA,5113,M,2015,1.456,0.113
779224,BEL,HKG,5113,X,2015,8.333,0.530
779225,BEL,IND,5113,M,2015,0.626,0.048
779226,BEL,ITA,5113,M,2015,8.176,0.633
779227,BEL,NLD,5113,X,2015,0.034,0.002
779228,BEL,NLD,5113,M,2015,3.260,0.253
779229,BEL,PRT,5113,X,2015,0.061,0.004
779230,BEL,TUR,5113,M,2015,0.058,0.005

In [155]:
outfile["HS4 [4 digit]"].unique()

array(['0101', '0102', '0103', '0104', '0105', '0106', '0201', '0202',
       '0203', '0204', '0205', '0206', '0207', '0208', '0209', '0210',
       '0301', '0302', '0303', '0304', '0305', '0306', '0307', '0308',
       '0401', '0402', '0403', '0404', '0405', '0406', '0407', '0408',
       '0409', '0410', '0501', '0502', '0503', '0504', '0505', '0506',
       '0507', '0508', '0509', '0510', '0511', '0601', '0602', '0603',
       '0604', '0701', '0702', '0703', '0704', '0705', '0706', '0707',
       '0708', '0709', '0710', '0711', '0712', '0713', '0714', '0801',
       '0802', '0803', '0804', '0805', '0806', '0807', '0808', '0809',
       '0810', '0811', '0812', '0813', '0814', '0901', '0902', '0903',
       '0904', '0905', '0906', '0907', '0908', '0909', '0910', '1001',
       '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1101',
       '1102', '1103', '1104', '1105', '1106', '1107', '1108', '1109',
       '1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208',
       '1209', '1210', '1211', '1212', '1213', '1214', '1301', '1302',
       '1401', '1402', '1403', '1404', '1501', '1502', '1503', '1504',
       '1505', '1506', '1507', '1508', '1509', '1510', '1511', '1512',
       '1513', '1514', '1515', '1516', '1517', '1518', '1520', '1521',
       '1522', '1601', '1602', '1603', '1604', '1605', '1701', '1702',
       '1703', '1704', '1801', '1802', '1803', '1804', '1805', '1806',
       '1901', '1902', '1903', '1904', '1905', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2101', '2102',
       '2103', '2104', '2105', '2106', '2201', '2202', '2203', '2204',
       '2205', '2206', '2207', '2208', '2209', '2301', '2302', '2303',
       '2304', '2305', '2306', '2307', '2308', '2309', '2401', '2402',
       '2403', '5001', '5002', '5003', '5004', '5005', '5006', '5007',
       '5101', '5102', '5103', '5104', '5105', '5106', '5107', '5108',
       '5109', '5110', '5111', '5112', '5113'], dtype=object)